### PR TITLE
create the media model

### PR DESCRIPTION
**Pull request by Dayakes**
code for media model needs review works on #4

### CODE REVIEW

**Comment by Dayakes** [comment]
noticed issue with code analysis and some typos. working on fixing those and updating the branch

**Comment by Dayakes** [comment]
fixes to code coverage and typos implemented. code ready to review

**Comment by fredbelotte** [comment]
is this ready?

**Comment by fredbelotte** [comment]
as discussed, we may need some changes here.

**Comment by Dayakes** [comment]
@fredbelotte this code is ready for review

**Comment by Dayakes** [comment]
closing this request for now until it is ready

**Pull request closed without merging**
